include: package:pedantic_mono/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*g.dart"
    - "*.g.dart"
  errors:
    mixin_inherits_from_not_object: ignore
    unused_import: error
    directives_ordering: error

linter:
  rules:
    avoid_classes_with_only_static_members: false
    prefer_constructors_over_static_methods: false
    avoid_function_literals_in_foreach_calls: false
    flutter_style_todos: false
    type_annotate_public_apis: false